### ISSUE TITLE
get /api/v1/menus/ returns id as a string value

### ISSUE THREAD

**Issue by leafes** [B1nC0D3/api_restaurant#1]
I've tested your API methods in swagger and found out that 
```
get /api/v1/menus/
```
returns JSON where id is a string value.
``` 
 {
    "title": "biba",
    "description": "boba",
    "id": "1", <-------
    "submenus_count": 0,
    "dishes_count": 0
  }
```
I suggest to work on that and change it to proper return id in methods as an integer

**Comment by B1nC0D3** [comment]
fixed in nested fileds branch
